<?php

namespace Costa\User\Entities;

use Costa\Package\Model\SerializeDateToIso8001;
use Costa\User\Notification\ResetPassword;
use Costa\User\Notification\UserSendPassword;
use Costa\User\Notification\VerifyEmail;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, SerializeDateToIso8001, SoftDeletes, HasRoles;

    protected $guard_name = 'web';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Send the password reset notification.
     *
     * @param string $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPassword($token));
    }

    public function sendEmailVerificationNotification()
    {
        $this->notify(new VerifyEmail());
    }

    public function sendEmailWithPassword($password, $isNew = true){
        $this->notify(new UserSendPassword($password, $isNew));
    }

    public function getRouteKeyName()
    {
        return config('costa_user.router.user');
    }

    public static function create($attributes)
    {
        $obj = parent::query()->create($attributes);
        $obj->syncRelations($attributes);
        return $obj;
    }

    public function update(array $attributes = [], array $options = [])
    {
        $obj = parent::update($attributes, $options); // TODO: Change the autogenerated stub
        $this->syncRelations($attributes);

        return $obj;
    }

    public function syncRelations($attributes){
        if(!empty($attributes['permissions'])){
            $this->syncPermissions($attributes['permissions']);
        }
        if(!empty($attributes['roles'])){
            $this->syncRoles($attributes['roles']);
        }
    }
}
